### ISSUE TITLE
.otf fonts gets wrong format

### ISSUE THREAD

**Issue by tobros91** [Dan503/font-face-generator#7]
When using a .otf font type, the format gets the wrong value.

Expected output
src: local("☺"), url(https://serneke-karlatornet.lndo.site:8080/cbb7485d8c63df71c318bc45a5268f05.otf) format("**opentype**");

Actual output
src: local("☺"), url(https://serneke-karlatornet.lndo.site:8080/cbb7485d8c63df71c318bc45a5268f05.otf) format("**otf**");

**Comment by Dan503** [comment]
Can you take a look at this PR and implement a similar fix for otf?

It is essentially the same issue but with a different font file type.

**Comment by Dan503** [comment]
Sorry forgot to post the link. 

This PR:
https://github.com/Dan503/font-face-generator/pull/6

**Comment by Dan503** [comment]
Released in v1.1.3
